KIND_ATTENDANCE_PENDING = 'ATTENDANCE_PENDING'
KIND_LESSON_TODAY = 'LESSON_TODAY'
KIND_LESSON_FINALIZE = 'LESSON_FINALIZE'
KIND_MAGAZINE_PAYMENT = 'MAGAZINE_PAYMENT'
KIND_BIRTHDAY_TODAY = 'BIRTHDAY_TODAY'

KIND_CHOICES = [
    (KIND_ATTENDANCE_PENDING, 'Chamada pendente'),
    (KIND_LESSON_TODAY, 'Aula hoje'),
    (KIND_LESSON_FINALIZE, 'Lição a finalizar'),
    (KIND_MAGAZINE_PAYMENT, 'Revista aguardando pagamento'),
    (KIND_BIRTHDAY_TODAY, 'Aniversário hoje'),
]

SEVERITY_INFO = 'info'
SEVERITY_WARNING = 'warning'

SEVERITY_CHOICES = [
    (SEVERITY_INFO, 'Info'),
    (SEVERITY_WARNING, 'Aviso'),
]
