"""Dados operacionais de EBD por igreja (turmas, alunos, lições)."""
from datetime import date


def _endereco(cep, rua, numero, bairro, cidade='Teresina'):
    return {'cep': cep, 'rua': rua, 'numero': numero, 'bairro': bairro, 'cidade': cidade, 'uf': 'PI'}


LESSON_TEMPLATES = [
    {
        'numero': 1,
        'tema': 'O Início da Jornada de Fé',
        'data': date(2026, 1, 4),
        'texto_aureo': 'Hebreus 11:1',
        'texto_biblico': 'Gênesis 12:1-9',
        'objetivo': 'Compreender o chamado de Abraão para uma vida de fé.',
        'status': 'FINALIZADA',
    },
    {
        'numero': 2,
        'tema': 'A Obediência que Transforma',
        'data': date(2026, 1, 11),
        'texto_aureo': 'Tiago 1:22',
        'texto_biblico': 'Êxodo 3:1-12',
        'objetivo': 'Aplicar princípios de obediência bíblica no cotidiano.',
        'status': 'FINALIZADA',
    },
    {
        'numero': 3,
        'tema': 'Serviço com Propósito',
        'data': date(2026, 1, 18),
        'texto_aureo': 'Marcos 10:45',
        'texto_biblico': 'Atos 6:1-7',
        'objetivo': 'Entender o valor do serviço cristão na igreja local.',
        'status': 'ABERTA',
    },
    {
        'numero': 4,
        'tema': 'Perseverança e Esperança',
        'data': date(2026, 1, 25),
        'texto_aureo': 'Romanos 5:3-5',
        'texto_biblico': 'Hebreus 12:1-3',
        'objetivo': 'Fortalecer a perseverança da turma diante dos desafios.',
        'status': 'ABERTA',
    },
]

TRIMESTERS_DATA = [
    {
        'numero': 1,
        'ano': 2026,
        'titulo': '1º Trimestre 2026',
        'data_inicio': date(2026, 1, 1),
        'data_fim': date(2026, 3, 31),
        'quantidade_licoes': 13,
        'status': 'EM_ANDAMENTO',
    },
    {
        'numero': 2,
        'ano': 2026,
        'titulo': '2º Trimestre 2026',
        'data_inicio': date(2026, 4, 1),
        'data_fim': date(2026, 6, 30),
        'quantidade_licoes': 13,
        'status': 'PLANEJADO',
    },
]


CHURCH_EBD_SEEDS = [
    {
        'org_key': 'ad_dirceu',
        'classes': [
            {'nome': 'Adultos I', 'faixa_etaria': '26-35 anos', 'cor': '#125A94', 'teacher_email': 'prof.adultos@adebd.com'},
            {'nome': 'Jovens', 'faixa_etaria': '18-25 anos', 'cor': '#0C7A43', 'teacher_email': 'prof.jovens@adebd.com'},
            {'nome': 'Adolescentes', 'faixa_etaria': '13-17 anos', 'cor': '#A76A00', 'teacher_email': 'secretaria@adebd.com'},
        ],
        'students': [
            {
                'nome': 'João Pedro Silva',
                'sexo': 'M',
                'data_nascimento': date(1995, 3, 15),
                'email': 'joao.dirceu@email.com',
                'telefone': '(86) 99901-1234',
                'turma': 'Adultos I',
                'endereco': _endereco('64001-000', 'Rua São Pedro', '123', 'Dirceu I'),
                'responsavel': {'nome': 'Maria da Silva', 'telefone': '(86) 98811-1122'},
            },
            {
                'nome': 'Mariana Lopes',
                'sexo': 'F',
                'data_nascimento': date(1998, 11, 8),
                'email': 'mariana.lopes@email.com',
                'telefone': '(86) 99844-7878',
                'turma': 'Adultos I',
                'endereco': _endereco('64053-120', 'Rua Coelho de Resende', '91', 'Centro'),
                'responsavel': {'nome': 'José Lopes', 'telefone': '(86) 99111-0055'},
            },
            {
                'nome': 'Lucas Andrade',
                'sexo': 'M',
                'data_nascimento': date(2003, 6, 2),
                'email': 'lucas.andrade@email.com',
                'telefone': '(86) 99922-5678',
                'turma': 'Jovens',
                'endereco': _endereco('64018-220', 'Av. Noé Mendes', '800', 'Renascença'),
                'responsavel': {'nome': 'Edna Andrade', 'telefone': '(86) 98999-4455'},
            },
            {
                'nome': 'Gabriela Santos',
                'sexo': 'F',
                'data_nascimento': date(2002, 4, 12),
                'email': 'gabriela.santos@email.com',
                'telefone': '(86) 99924-1001',
                'turma': 'Jovens',
                'endereco': _endereco('64018-301', 'Rua Darcy Viana', '156', 'Renascença'),
                'responsavel': {'nome': 'Rosa Santos', 'telefone': '(86) 98824-1001'},
            },
            {
                'nome': 'Matheus Oliveira',
                'sexo': 'M',
                'data_nascimento': date(2001, 9, 28),
                'email': 'matheus.oliveira@email.com',
                'telefone': '(86) 99924-1002',
                'turma': 'Jovens',
                'endereco': _endereco('64019-110', 'Rua João Cabral', '402', 'São Cristóvão'),
                'responsavel': {'nome': 'Antônio Oliveira', 'telefone': '(86) 98824-1002'},
            },
            {
                'nome': 'Isabela Ferreira',
                'sexo': 'F',
                'data_nascimento': date(2004, 2, 7),
                'email': 'isabela.ferreira@email.com',
                'telefone': '(86) 99924-1003',
                'turma': 'Jovens',
                'endereco': _endereco('64020-205', 'Rua Almirante Tamandaré', '78', 'Fátima'),
                'responsavel': {'nome': 'Cláudia Ferreira', 'telefone': '(86) 98824-1003'},
            },
            {
                'nome': 'Vinícius Ribeiro',
                'sexo': 'M',
                'data_nascimento': date(2000, 11, 19),
                'email': 'vinicius.ribeiro@email.com',
                'telefone': '(86) 99924-1004',
                'turma': 'Jovens',
                'endereco': _endereco('64021-330', 'Av. Maranhão', '950', 'Centro'),
                'responsavel': {'nome': 'Márcio Ribeiro', 'telefone': '(86) 98824-1004'},
            },
            {
                'nome': 'Larissa Mendes',
                'sexo': 'F',
                'data_nascimento': date(2003, 7, 3),
                'email': 'larissa.mendes@email.com',
                'telefone': '(86) 99924-1005',
                'turma': 'Jovens',
                'endereco': _endereco('64022-415', 'Rua Desembargador Freitas', '210', 'Ilhotas'),
                'responsavel': {'nome': 'Solange Mendes', 'telefone': '(86) 98824-1005'},
            },
            {
                'nome': 'Diego Carvalho',
                'sexo': 'M',
                'data_nascimento': date(2002, 12, 15),
                'email': 'diego.carvalho@email.com',
                'telefone': '(86) 99924-1006',
                'turma': 'Jovens',
                'endereco': _endereco('64023-520', 'Rua Barroso', '33', 'Dirceu II'),
                'responsavel': {'nome': 'Helena Carvalho', 'telefone': '(86) 98824-1006'},
            },
            {
                'nome': 'Amanda Pires',
                'sexo': 'F',
                'data_nascimento': date(2004, 5, 22),
                'email': 'amanda.pires@email.com',
                'telefone': '(86) 99924-1007',
                'turma': 'Jovens',
                'endereco': _endereco('64024-625', 'Rua São João', '512', 'Parque Piauí'),
                'responsavel': {'nome': 'Francisco Pires', 'telefone': '(86) 98824-1007'},
            },
            {
                'nome': 'Ricardo Nascimento',
                'sexo': 'M',
                'data_nascimento': date(2001, 1, 30),
                'email': 'ricardo.nascimento@email.com',
                'telefone': '(86) 99924-1008',
                'turma': 'Jovens',
                'endereco': _endereco('64025-730', 'Rua Artur de Vasconcelos', '189', 'Itararé'),
                'responsavel': {'nome': 'Vera Nascimento', 'telefone': '(86) 98824-1008'},
            },
            {
                'nome': 'Carlos Eduardo Lima',
                'sexo': 'M',
                'data_nascimento': date(1994, 8, 3),
                'email': 'carlos.lima@email.com',
                'telefone': '(86) 99902-3344',
                'turma': 'Adultos I',
                'endereco': _endereco('64052-200', 'Rua Rui Barbosa', '220', 'Centro'),
                'responsavel': {'nome': 'Eduarda Lima', 'telefone': '(86) 98802-3344'},
            },
            {
                'nome': 'Fernanda Araújo',
                'sexo': 'F',
                'data_nascimento': date(1996, 12, 19),
                'email': 'fernanda.araujo@email.com',
                'telefone': '(86) 99902-3355',
                'turma': 'Adultos I',
                'endereco': _endereco('64053-310', 'Rua Almirante Gomes', '67', 'Centro'),
                'responsavel': {'nome': 'Roberto Araújo', 'telefone': '(86) 98802-3355'},
            },
            {
                'nome': 'Beatriz Costa',
                'sexo': 'F',
                'data_nascimento': date(2008, 1, 10),
                'email': 'beatriz.costa@email.com',
                'telefone': '(86) 99933-9876',
                'turma': 'Adolescentes',
                'endereco': _endereco('64025-430', 'Rua Projetada', '45', 'Itararé'),
                'responsavel': {'nome': 'Paulo Costa', 'telefone': '(86) 98777-1234'},
            },
        ],
    },
    {
        'org_key': 'ad_centro',
        'classes': [
            {'nome': 'Adultos', 'faixa_etaria': '26-40 anos', 'cor': '#1D4ED8', 'teacher_email': 'secretaria.centro@adebd.com'},
            {'nome': 'Jovens', 'faixa_etaria': '18-25 anos', 'cor': '#059669', 'teacher_email': 'secretaria.centro@adebd.com'},
            {'nome': 'Crianças', 'faixa_etaria': '6-12 anos', 'cor': '#DB2777', 'teacher_email': 'secretaria.centro@adebd.com'},
        ],
        'students': [
            {
                'nome': 'Fernando Almeida',
                'sexo': 'M',
                'data_nascimento': date(1992, 7, 20),
                'email': 'fernando.centro@email.com',
                'telefone': '(86) 99100-1100',
                'turma': 'Adultos',
                'endereco': _endereco('64000-100', 'Rua Areolino de Abreu', '500', 'Centro'),
                'responsavel': {'nome': 'Lúcia Almeida', 'telefone': '(86) 98800-1100'},
            },
            {
                'nome': 'Patrícia Nunes',
                'sexo': 'F',
                'data_nascimento': date(1990, 2, 14),
                'email': 'patricia.centro@email.com',
                'telefone': '(86) 99200-2200',
                'turma': 'Adultos',
                'endereco': _endereco('64001-200', 'Rua Coelho Rodrigues', '88', 'Centro'),
                'responsavel': {'nome': 'Raimundo Nunes', 'telefone': '(86) 98700-2200'},
            },
            {
                'nome': 'Rafael Souza',
                'sexo': 'M',
                'data_nascimento': date(2004, 9, 5),
                'email': 'rafael.centro@email.com',
                'telefone': '(86) 99300-3300',
                'turma': 'Jovens',
                'endereco': _endereco('64010-300', 'Rua Poti', '210', 'Fátima'),
                'responsavel': {'nome': 'Sônia Souza', 'telefone': '(86) 98600-3300'},
            },
            {
                'nome': 'Camila Rocha',
                'sexo': 'F',
                'data_nascimento': date(2005, 4, 18),
                'email': 'camila.centro@email.com',
                'telefone': '(86) 99400-4400',
                'turma': 'Jovens',
                'endereco': _endereco('64015-400', 'Av. Frei Serafim', '1200', 'Centro'),
                'responsavel': {'nome': 'Marcos Rocha', 'telefone': '(86) 98500-4400'},
            },
            {
                'nome': 'Pedro Henrique',
                'sexo': 'M',
                'data_nascimento': date(2016, 12, 1),
                'email': 'pedro.centro@email.com',
                'telefone': '(86) 99500-5500',
                'turma': 'Crianças',
                'endereco': _endereco('64020-500', 'Rua Pedro II', '45', 'Ilhotas'),
                'responsavel': {'nome': 'Ana Paula', 'telefone': '(86) 98400-5500'},
            },
        ],
    },
    {
        'org_key': 'congregacao_vila_nova',
        'classes': [
            {'nome': 'Família', 'faixa_etaria': 'Adultos', 'cor': '#7C3AED', 'teacher_email': 'secretaria.vilanova@adebd.com'},
            {'nome': 'Adolescentes', 'faixa_etaria': '13-17 anos', 'cor': '#EA580C', 'teacher_email': 'secretaria.vilanova@adebd.com'},
        ],
        'students': [
            {
                'nome': 'Antônio Vila Nova',
                'sexo': 'M',
                'data_nascimento': date(1988, 5, 9),
                'email': 'antonio.vn@email.com',
                'telefone': '(86) 99610-1010',
                'turma': 'Família',
                'endereco': _endereco('64012-600', 'Rua Vila Nova', '300', 'Vila Nova'),
                'responsavel': {'nome': 'Francisca Vila', 'telefone': '(86) 98110-1010'},
            },
            {
                'nome': 'Juliana Martins',
                'sexo': 'F',
                'data_nascimento': date(1993, 8, 22),
                'email': 'juliana.vn@email.com',
                'telefone': '(86) 99620-2020',
                'turma': 'Família',
                'endereco': _endereco('64012-610', 'Rua das Flores', '77', 'Vila Nova'),
                'responsavel': {'nome': 'Carlos Martins', 'telefone': '(86) 98220-2020'},
            },
            {
                'nome': 'Thiago Pereira',
                'sexo': 'M',
                'data_nascimento': date(2010, 3, 3),
                'email': 'thiago.vn@email.com',
                'telefone': '(86) 99630-3030',
                'turma': 'Adolescentes',
                'endereco': _endereco('64012-620', 'Rua do Campo', '12', 'Vila Nova'),
                'responsavel': {'nome': 'Rita Pereira', 'telefone': '(86) 98330-3030'},
            },
        ],
    },
    {
        'org_key': 'ad_parnaiba_centro',
        'classes': [
            {'nome': 'Adultos', 'faixa_etaria': 'Adultos', 'cor': '#0369A1', 'teacher_email': 'secretaria.parnaiba@adebd.com'},
            {'nome': 'Jovens e Adolescentes', 'faixa_etaria': '13-25 anos', 'cor': '#16A34A', 'teacher_email': 'secretaria.parnaiba@adebd.com'},
        ],
        'students': [
            {
                'nome': 'Eduardo Parnaíba',
                'sexo': 'M',
                'data_nascimento': date(1985, 1, 30),
                'email': 'eduardo.parnaiba@email.com',
                'telefone': '(86) 99820-2020',
                'turma': 'Adultos',
                'endereco': _endereco('64200-100', 'Rua São Benedito', '400', 'Centro', 'Parnaíba'),
                'responsavel': {'nome': 'Marta Parnaíba', 'telefone': '(86) 98820-2020'},
            },
            {
                'nome': 'Silvia Costa',
                'sexo': 'F',
                'data_nascimento': date(1991, 6, 11),
                'email': 'silvia.parnaiba@email.com',
                'telefone': '(86) 99830-3030',
                'turma': 'Adultos',
                'endereco': _endereco('64202-200', 'Av. São Sebastião', '900', 'Centro', 'Parnaíba'),
                'responsavel': {'nome': 'João Costa', 'telefone': '(86) 98730-3030'},
            },
            {
                'nome': 'Gabriel Lima',
                'sexo': 'M',
                'data_nascimento': date(2007, 10, 25),
                'email': 'gabriel.parnaiba@email.com',
                'telefone': '(86) 99840-4040',
                'turma': 'Jovens e Adolescentes',
                'endereco': _endereco('64205-300', 'Rua do Porto', '55', 'Pindorama', 'Parnaíba'),
                'responsavel': {'nome': 'Eliane Lima', 'telefone': '(86) 98640-4040'},
            },
        ],
    },
    {
        'org_key': 'ad_standalone',
        'classes': [
            {'nome': 'Adultos', 'faixa_etaria': 'Adultos', 'cor': '#4F46E5', 'teacher_email': 'secretaria.standalone@adebd.com'},
            {'nome': 'Jovens', 'faixa_etaria': '18-25 anos', 'cor': '#0D9488', 'teacher_email': 'secretaria.standalone@adebd.com'},
        ],
        'students': [
            {
                'nome': 'Roberto Standalone',
                'sexo': 'M',
                'data_nascimento': date(1987, 4, 4),
                'email': 'roberto.standalone@email.com',
                'telefone': '(86) 99770-7070',
                'turma': 'Adultos',
                'endereco': _endereco('64055-700', 'Rua Independência', '200', 'São Cristóvão'),
                'responsavel': {'nome': 'Tereza Standalone', 'telefone': '(86) 98770-7070'},
            },
            {
                'nome': 'Amanda Freitas',
                'sexo': 'F',
                'data_nascimento': date(1994, 11, 19),
                'email': 'amanda.standalone@email.com',
                'telefone': '(86) 99780-8080',
                'turma': 'Adultos',
                'endereco': _endereco('64055-710', 'Rua das Acácias', '33', 'São Cristóvão'),
                'responsavel': {'nome': 'Paulo Freitas', 'telefone': '(86) 98680-8080'},
            },
            {
                'nome': 'Diego Melo',
                'sexo': 'M',
                'data_nascimento': date(2002, 2, 28),
                'email': 'diego.standalone@email.com',
                'telefone': '(86) 99790-9090',
                'turma': 'Jovens',
                'endereco': _endereco('64055-720', 'Av. João XXIII', '1500', 'Morada Nova'),
                'responsavel': {'nome': 'Célia Melo', 'telefone': '(86) 98590-9090'},
            },
        ],
    },
]
