# Generated by Django 5.1.6 on 2026-07-25 02:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_rename_organizatio_parent__idx_organizatio_parent__c2cd70_idx_and_more'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_sha256', models.CharField(max_length=64)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(choices=[('INVALID', 'Inválido'), ('VALIDATED', 'Validado'), ('CONFIRMED', 'Confirmado'), ('UNDONE', 'Desfeito'), ('PARTIALLY_UNDONE', 'Parcialmente desfeito')], max_length=30)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('valid_rows', models.PositiveIntegerField(default=0)),
                ('invalid_rows', models.PositiveIntegerField(default=0)),
                ('created_students', models.PositiveIntegerField(default=0)),
                ('ignored_columns', models.JSONField(blank=True, default=list)),
                ('missing_columns', models.JSONField(blank=True, default=list)),
                ('file_errors', models.JSONField(blank=True, default=list)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('undone_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_imports_confirmed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('undone_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_imports_undone', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StudentImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('VALID', 'Válido'), ('INVALID', 'Inválido'), ('CREATED', 'Criado'), ('FAILED', 'Falhou ao confirmar'), ('UNDONE', 'Desfeito'), ('UNDO_SKIPPED', 'Não desfeito')], max_length=30)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('student_version_at_confirm', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='students.studentimportbatch')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_rows', to='students.student')),
            ],
            options={
                'ordering': ['row_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StudentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Criado'), ('UPDATED', 'Atualizado'), ('DEACTIVATED', 'Inativado'), ('RESTORED', 'Restaurado'), ('IMPORTED', 'Importado'), ('IMPORT_UNDONE', 'Importação desfeita')], max_length=30)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_history_events', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico', to='students.student')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['student', '-created_at'], name='students_st_student_1bcdcb_idx'), models.Index(fields=['organization', '-created_at'], name='students_st_organiz_8f6307_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='studentimportbatch',
            index=models.Index(fields=['organization', '-created_at'], name='students_st_organiz_98b0e0_idx'),
        ),
        migrations.AddIndex(
            model_name='studentimportbatch',
            index=models.Index(fields=['organization', 'status'], name='students_st_organiz_f7fc9b_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentimportrow',
            constraint=models.UniqueConstraint(fields=('batch', 'row_number'), name='unique_student_import_batch_row'),
        ),
    ]
