# Generated by Django 5.1.6 on 2026-05-29 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organization_campo_igreja_formato'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='organization',
            new_name='organizatio_parent__c2cd70_idx',
            old_name='organizatio_parent__idx',
        ),
        migrations.RenameIndex(
            model_name='organization',
            new_name='organizatio_tipo_753e0b_idx',
            old_name='organizatio_tipo_idx',
        ),
        migrations.RenameIndex(
            model_name='organization',
            new_name='organizatio_formato_44ca79_idx',
            old_name='organizatio_formato_idx',
        ),
    ]
