# Generated by Django 5.1.6 on 2026-06-02 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_415907_idx',
            old_name='notificatio_user_id_8e0f0d_idx',
        ),
    ]
