PAYMENT_METHOD_DINHEIRO = 'DINHEIRO'
PAYMENT_METHOD_PIX = 'PIX'
PAYMENT_METHOD_CARTAO = 'CARTAO'
PAYMENT_METHOD_TRANSFERENCIA = 'TRANSFERENCIA'
PAYMENT_METHOD_OUTRO = 'OUTRO'

PAYMENT_METHOD_CHOICES = [
    (PAYMENT_METHOD_DINHEIRO, 'Dinheiro'),
    (PAYMENT_METHOD_PIX, 'PIX'),
    (PAYMENT_METHOD_CARTAO, 'Cartão'),
    (PAYMENT_METHOD_TRANSFERENCIA, 'Transferência'),
    (PAYMENT_METHOD_OUTRO, 'Outro'),
]

PAYMENT_METHOD_LABELS = dict(PAYMENT_METHOD_CHOICES)
