# Generated by Django 5.1.6 on 2026-03-31 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_trimester'),
    ]

    operations = [
        migrations.AddField(
            model_name='trimester',
            name='quantidade_licoes',
            field=models.PositiveSmallIntegerField(default=13),
        ),
    ]
