# Generated by Django 5.1.6 on 2026-09-14 12:20

import django.db.models.deletion
import lessons.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_lessonschedule'),
        ('organizations', '0004_rename_organizatio_parent__idx_organizatio_parent__c2cd70_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('arquivo', models.FileField(upload_to=lessons.models.lesson_attachment_path)),
                ('nome_original', models.CharField(max_length=255)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('tamanho', models.PositiveBigIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='lessons.lesson')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['lesson', 'is_active'], name='lessons_les_lesson__02aab4_idx')],
            },
        ),
    ]
