ROLE_ADMINISTRADOR = 'ADMINISTRADOR'
ROLE_SECRETARIO_CAMPO = 'SECRETARIO_CAMPO'
ROLE_SECRETARIO_IGREJA = 'SECRETARIO_IGREJA'
ROLE_PROFESSOR = 'PROFESSOR'

CANONICAL_ROLES = (
    ROLE_ADMINISTRADOR,
    ROLE_SECRETARIO_CAMPO,
    ROLE_SECRETARIO_IGREJA,
    ROLE_PROFESSOR,
)

ADMIN_ROLES = {ROLE_ADMINISTRADOR}
SECRETARY_ROLES = {ROLE_SECRETARIO_CAMPO, ROLE_SECRETARIO_IGREJA}
FULL_OPERATIONAL_ROLES = ADMIN_ROLES | SECRETARY_ROLES

ROLE_LABELS = {
    ROLE_ADMINISTRADOR: 'Administrador do sistema',
    ROLE_SECRETARIO_CAMPO: 'Secretário de Campo',
    ROLE_SECRETARIO_IGREJA: 'Secretário de Igreja',
    ROLE_PROFESSOR: 'Professor',
}

LEGACY_ROLE_ALIASES = {
    'ADMINISTRADOR_CAMPO': ROLE_SECRETARIO_CAMPO,
    'SECRETARIA': ROLE_SECRETARIO_IGREJA,
    'ADMIN_IGREJA': ROLE_SECRETARIO_IGREJA,
    'SECRETARIO_IGREJA': ROLE_SECRETARIO_IGREJA,
    'SECRETÁRIO DE IGREJA': ROLE_SECRETARIO_IGREJA,
}

MODULES = (
    'usuarios',
    'organizacoes',
    'turmas',
    'alunos',
    'licoes',
    'frequencia',
    'financeiro',
    'revistas',
    'dashboard',
)

ROLE_MODULE_MATRIX = {
    ROLE_ADMINISTRADOR: MODULES,
    ROLE_SECRETARIO_CAMPO: MODULES,
    ROLE_SECRETARIO_IGREJA: MODULES,
    ROLE_PROFESSOR: ('dashboard', 'alunos', 'licoes', 'frequencia', 'turmas'),
}

OPERATIONAL_ORG_TYPES = ('IGREJA',)
# Legado até migração completa em todos os ambientes
OPERATIONAL_ORG_TYPES_LEGACY = ('FILIAL', 'CONGREGACAO')
